-- CAP
WITH e AS (SELECT id FROM examens WHERE nom = 'CAP' AND systeme_educatif_id = 1)
INSERT INTO series_filieres (examen_id, nom, groupe) VALUES
  ((SELECT id FROM e), 'Agronomie', 'Agro-sylvo-pastoral'),
  ((SELECT id FROM e), 'Zootechnie', 'Agro-sylvo-pastoral'),
  ((SELECT id FROM e), 'Construction métallique', 'Génie civil'),
  ((SELECT id FROM e), 'Maçonnerie / Construction', 'Génie civil'),
  ((SELECT id FROM e), 'Maçonnerie / Dessin', 'Génie civil'),
  ((SELECT id FROM e), 'Menuiserie / Bois', 'Génie civil'),
  ((SELECT id FROM e), 'Électromécanique', 'Génie électrique'),
  ((SELECT id FROM e), 'Électronique', 'Génie électrique'),
  ((SELECT id FROM e), 'Monteur-électricien', 'Génie électrique'),
  ((SELECT id FROM e), 'Mécanique automobile', 'Génie mécanique'),
  ((SELECT id FROM e), 'Mécanique générale', 'Génie mécanique'),
  ((SELECT id FROM e), 'Broderie', 'Matériaux souples'),
  ((SELECT id FROM e), 'Coupe-couture', 'Matériaux souples'),
  ((SELECT id FROM e), 'Tissage', 'Matériaux souples'),
  ((SELECT id FROM e), 'Habillement', 'Matériaux souples'),
  ((SELECT id FROM e), 'Fabrication industrielle', 'Matériaux souples'),
  ((SELECT id FROM e), 'Économie familiale et rurale', 'Hygiène-environnement'),
  ((SELECT id FROM e), 'Petite enfance', 'Socio-sanitaire');

-- BEP
WITH e AS (SELECT id FROM examens WHERE nom = 'BEP' AND systeme_educatif_id = 1)
INSERT INTO series_filieres (examen_id, nom, groupe) VALUES
  ((SELECT id FROM e), 'Bureautique - Secrétariat', 'Administration / Secrétariat'),
  ((SELECT id FROM e), 'Secrétariat / Bureautique', 'Administration / Secrétariat'),
  ((SELECT id FROM e), 'Communication administrative et secrétariat', 'Administration / Secrétariat'),
  ((SELECT id FROM e), 'Sténodactylographie', 'Administration / Secrétariat'),
  ((SELECT id FROM e), 'Employé de bureau', 'Administration / Secrétariat'),
  ((SELECT id FROM e), 'Comptabilité', 'Comptabilité / Gestion'),
  ((SELECT id FROM e), 'Bureautique - Comptabilité', 'Comptabilité / Gestion'),
  ((SELECT id FROM e), 'Comptabilité / Informatique', 'Comptabilité / Gestion'),
  ((SELECT id FROM e), 'Administration commerciale et comptable', 'Comptabilité / Gestion'),
  ((SELECT id FROM e), 'Administration commerciale et comptable (ACC)', 'Comptabilité / Gestion'),
  ((SELECT id FROM e), 'Techniques de Vente et de Commerce (TVC)', 'Commerce'),
  ((SELECT id FROM e), 'Transit', 'Commerce'),
  ((SELECT id FROM e), 'Déclarant en douane', 'Commerce'),
  ((SELECT id FROM e), 'Employé de banque', 'Commerce'),
  ((SELECT id FROM e), 'Informatique', 'Informatique'),
  ((SELECT id FROM e), 'Communication', 'Communication'),
  ((SELECT id FROM e), 'Hôtellerie', 'Hôtellerie / Restauration'),
  ((SELECT id FROM e), 'Hôtellerie-Restauration', 'Hôtellerie / Restauration'),
  ((SELECT id FROM e), 'Cuisine', 'Hôtellerie / Restauration'),
  ((SELECT id FROM e), 'Agroalimentaire', 'Agroalimentaire'),
  ((SELECT id FROM e), 'Économie sociale', 'Social / Santé'),
  ((SELECT id FROM e), 'Carrières sanitaires et sociales', 'Social / Santé'),
  ((SELECT id FROM e), 'Petite enfance', 'Social / Santé'),
  ((SELECT id FROM e), 'Optique et lunetterie', 'Social / Santé');

-- BAC
WITH e AS (SELECT id FROM examens WHERE nom = 'BAC' AND systeme_educatif_id = 1)
INSERT INTO series_filieres (examen_id, nom, groupe) VALUES
  ((SELECT id FROM e), 'A — Lettres / Philosophie', 'BAC Général'),
  ((SELECT id FROM e), 'C — Mathématiques / Physique-Chimie', 'BAC Général'),
  ((SELECT id FROM e), 'D — Mathématiques / Sciences de la Vie et de la Terre', 'BAC Général'),
  ((SELECT id FROM e), 'E — Mathématiques et Techniques', 'BAC Technique'),
  ((SELECT id FROM e), 'F1 — Construction mécanique', 'BAC Technique'),
  ((SELECT id FROM e), 'F2 — Électronique', 'BAC Technique'),
  ((SELECT id FROM e), 'F3 — Électrotechnique', 'BAC Technique'),
  ((SELECT id FROM e), 'G1 — Techniques administratives / Secrétariat', 'BAC Technique'),
  ((SELECT id FROM e), 'G2 — Techniques quantitatives / Comptabilité', 'BAC Technique'),
  ((SELECT id FROM e), 'H — Informatique', 'BAC Technique');

-- BTS
WITH e AS (SELECT id FROM examens WHERE nom = 'BTS' AND systeme_educatif_id = 1)
INSERT INTO series_filieres (examen_id, nom, groupe) VALUES
  ((SELECT id FROM e), 'Agriculture', 'Agriculture / Agroalimentaire'),
  ((SELECT id FROM e), 'Agroalimentaire', 'Agriculture / Agroalimentaire'),
  ((SELECT id FROM e), 'Agroéconomie', 'Agriculture / Agroalimentaire'),
  ((SELECT id FROM e), 'Gestion des Ressources Humaines', 'Administration / Gestion'),
  ((SELECT id FROM e), 'Marketing et Gestion Commerciale', 'Administration / Gestion'),
  ((SELECT id FROM e), 'Marketing Management', 'Administration / Gestion'),
  ((SELECT id FROM e), 'Banque et Microfinance', 'Banque / Finance'),
  ((SELECT id FROM e), 'Assurance Banque Finance', 'Banque / Finance'),
  ((SELECT id FROM e), 'Finance-Comptabilité', 'Banque / Finance'),
  ((SELECT id FROM e), 'Commerce International', 'Commerce'),
  ((SELECT id FROM e), 'Gestion Commerciale', 'Commerce'),
  ((SELECT id FROM e), 'Communication d''Entreprise', 'Communication'),
  ((SELECT id FROM e), 'Ressources Humaines et Communication', 'Communication'),
  ((SELECT id FROM e), 'Informatique de Gestion', 'Informatique'),
  ((SELECT id FROM e), 'Informatique et Développement d''Applications', 'Informatique'),
  ((SELECT id FROM e), 'Système d''Information et Réseaux', 'Informatique'),
  ((SELECT id FROM e), 'Systèmes d''Information et Réseaux', 'Informatique'),
  ((SELECT id FROM e), 'Réseaux Informatiques et Télécommunications', 'Informatique'),
  ((SELECT id FROM e), 'Statistiques et Informatique', 'Informatique'),
  ((SELECT id FROM e), 'Électrotechnique', 'Électricité / Électronique'),
  ((SELECT id FROM e), 'Électronique', 'Électricité / Électronique'),
  ((SELECT id FROM e), 'Génie Électrique', 'Électricité / Électronique'),
  ((SELECT id FROM e), 'Génie Électrique - Électromécanique', 'Électricité / Électronique'),
  ((SELECT id FROM e), 'Génie Électrique - Informatique Industrielle', 'Électricité / Électronique'),
  ((SELECT id FROM e), 'Électronique et Informatique Industrielle', 'Électricité / Électronique'),
  ((SELECT id FROM e), 'Génie Électronique et Informatique Industrielle', 'Électricité / Électronique'),
  ((SELECT id FROM e), 'Maintenance Industrielle', 'Mécanique / Maintenance'),
  ((SELECT id FROM e), 'Génie Industriel et Maintenance', 'Mécanique / Maintenance'),
  ((SELECT id FROM e), 'Génie Mécanique et Productique', 'Mécanique / Maintenance'),
  ((SELECT id FROM e), 'Bâtiment et Travaux Publics', 'Génie civil / BTP'),
  ((SELECT id FROM e), 'Géomètre-Topographe', 'Génie civil / BTP'),
  ((SELECT id FROM e), 'Génie Minier', 'Mines / Pétrole'),
  ((SELECT id FROM e), 'Pétrole-Exploration', 'Mines / Pétrole'),
  ((SELECT id FROM e), 'Pétrole-Pétrochimie', 'Mines / Pétrole'),
  ((SELECT id FROM e), 'Pétrole-Exploitation', 'Mines / Pétrole'),
  ((SELECT id FROM e), 'Génie Biomédical', 'Santé / Biomédical'),
  ((SELECT id FROM e), 'Environnement et Foresterie', 'Environnement'),
  ((SELECT id FROM e), 'Hôtellerie', 'Hôtellerie / Tourisme'),
  ((SELECT id FROM e), 'Tourisme', 'Hôtellerie / Tourisme'),
  ((SELECT id FROM e), 'Tourisme et Hôtellerie', 'Hôtellerie / Tourisme'),
  ((SELECT id FROM e), 'Transport et Logistique', 'Transport / Logistique'),
  ((SELECT id FROM e), 'Logistique', 'Transport / Logistique'),
  ((SELECT id FROM e), 'Secrétariat de Direction', 'Secrétariat / Documentation'),
  ((SELECT id FROM e), 'Secrétariat de Direction Bureautique', 'Secrétariat / Documentation'),
  ((SELECT id FROM e), 'Archives', 'Secrétariat / Documentation'),
  ((SELECT id FROM e), 'Bibliothèque', 'Secrétariat / Documentation');